// Schéma Protobuf du snapshot — deuxième format de l'axe I/O.
//
// Il corrige les deux défauts les plus coûteux du format JSON :
//   [S1] plus de nom de champ répété par case — le wire format n'écrit que des
//        numéros de champ ;
//   [S3] plus d'encodage texte — les entiers sont en varint.
//
// Il en conserve un, volontairement, pour que la comparaison avec le format
// bit-packé reste parlante :
//   [S2] le décor (terrain, vent) est toujours réécrit à chaque snapshot.
//
// Les quatre grilles sont des champs `repeated uint32` marqués [packed = true] :
// sans cela, Protobuf réécrirait l'étiquette du champ devant chaque valeur.
// Régénérer avec : make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: snapshot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Turn   uint32                 `protobuf:"varint,1,opt,name=turn,proto3" json:"turn,omitempty"`
	Width  uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Grilles en ordre ligne par ligne : index = y * width + x.
	// Chaque valeur tient sur 2 bits, mais le plus petit varint fait un octet :
	// c'est précisément la limite que le format bit-packé lèvera.
	Terrain       []uint32 `protobuf:"varint,4,rep,packed,name=terrain,proto3" json:"terrain,omitempty"`
	Wind          []uint32 `protobuf:"varint,5,rep,packed,name=wind,proto3" json:"wind,omitempty"`
	Fire          []uint32 `protobuf:"varint,6,rep,packed,name=fire,proto3" json:"fire,omitempty"`
	Rest          []uint32 `protobuf:"varint,7,rep,packed,name=rest,proto3" json:"rest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *Snapshot) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Snapshot) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Snapshot) GetTerrain() []uint32 {
	if x != nil {
		return x.Terrain
	}
	return nil
}

func (x *Snapshot) GetWind() []uint32 {
	if x != nil {
		return x.Wind
	}
	return nil
}

func (x *Snapshot) GetFire() []uint32 {
	if x != nil {
		return x.Fire
	}
	return nil
}

func (x *Snapshot) GetRest() []uint32 {
	if x != nil {
		return x.Rest
	}
	return nil
}

var File_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x0esnapshot.proto\x12\x14wildfire.snapshot.v1\"\xb2\x01\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04turn\x18\x01 \x01(\rR\x04turn\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x1c\n" +
	"\aterrain\x18\x04 \x03(\rB\x02\x10\x01R\aterrain\x12\x16\n" +
	"\x04wind\x18\x05 \x03(\rB\x02\x10\x01R\x04wind\x12\x16\n" +
	"\x04fire\x18\x06 \x03(\rB\x02\x10\x01R\x04fire\x12\x16\n" +
	"\x04rest\x18\a \x03(\rB\x02\x10\x01R\x04restB#Z!gol-wildfire/internal/snapshot/pbb\x06proto3"

var (
	file_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_proto_rawDescData []byte
)

func file_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)))
	})
	return file_snapshot_proto_rawDescData
}

var file_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_snapshot_proto_goTypes = []any{
	(*Snapshot)(nil), // 0: wildfire.snapshot.v1.Snapshot
}
var file_snapshot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snapshot_proto_init() }
func file_snapshot_proto_init() {
	if File_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_proto_depIdxs,
		MessageInfos:      file_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_proto = out.File
	file_snapshot_proto_goTypes = nil
	file_snapshot_proto_depIdxs = nil
}
